name: lab_testing_project
description: A Flutter project for all testing tasks.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Needed only if some tasks use Material or Widgets
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For mocking in Task 4
  mockito: ^5.4.4
  build_runner: ^2.4.8

  # For integration tests in Task 8
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
